### ISSUE TITLE
 File contains no section headers.

### ISSUE THREAD

**Issue by Macile** [pengchenglin/ATX-Test#3]
只修改了配置中的ATX2的地址，不知道为什么会报错
![TIM图片20190513114923](https://user-images.githubusercontent.com/26572845/57595153-03b07f00-7576-11e9-8972-0ddbebd20445.png)

**Comment by pengchenglin** [comment]
token也要改的




|
林鹏程
m170587788@163.com
|

签名由 网易邮箱大师 定制

On 05/13/2019 11:55, gtw wrote:

只修改了配置中的ATX2的地址，不知道为什么会报错

**Comment by Macile** [comment]
token也改了呀，和那个应该没有关系吧

**Comment by pengchenglin** [comment]
可能config.ini写的格式有问题吧 


|
林鹏程
m170587788@163.com
|

签名由 网易邮箱大师 定制

On 05/13/2019 12:07, gtw wrote:

token也改了呀，和那个应该没有关系吧

**Comment by Macile** [comment]
不是呀，完全没改变格式，

**Comment by pengchenglin** [comment]
看报错就是读token的时候出错的 你改改看


|
林鹏程
m170587788@163.com
|

签名由 网易邮箱大师 定制

On 05/13/2019 12:12, gtw wrote:

不是呀，完全没改变格式，

**Comment by Macile** [comment]
不是读token的时候报错，是因为config.ini的格式问题，调整成了utf8就可以了。但是现在又报了另外一个错误
Traceback (most recent call last):
  File "D:\ATX-Test-master\run_all_cases.py", line 17, in <module>
    cases = cs.collect_cases(suite=True)
  File "D:\ATX-Test-master\Public\CaseStrategy.py", line 36, in collect_cases
    self._collect_cases(cases, top_dir=test_suite)
  File "D:\ATX-Test-master\Public\CaseStrategy.py", line 13, in _collect_cases
    pattern=self.case_pattern, top_level_dir=top_dir)
  File "D:\Python\lib\unittest\loader.py", line 306, in discover
    os.path.dirname((the_module.__file__)))
  File "D:\Python\lib\ntpath.py", line 222, in dirname
    return split(p)[0]
  File "D:\Python\lib\ntpath.py", line 184, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

我把p的内容打印了出来发现是这样的
D:\ATX-Test-master\run_all_cases.py
D:\ATX-Test-master\run_all_cases.py
D:\Python\lib\site-packages\humanize\i18n.py
D:\Python\lib\site-packages\certifi\core.py
D:\ATX-Test-master\Public\ReadConfig.py
D:\Python\lib\site-packages\selenium\webdriver\remote\__init__.py
D:\Python\lib\site-packages\selenium\webdriver\remote\__init__.py
D:\ATX-Test-master\Public\Test_data.py
D:\ATX-Test-master\Public\maxim_monkey.py
D:\ATX-Test-master\Public\Report.py
None

**Comment by Macile** [comment]
我的测试用例很简单，里面只有两句话
import os
os.popen("adb devices")

**Comment by pengchenglin** [comment]
测试用例要按照unitest的格式要求来写


|
林鹏程
m170587788@163.com
|
签名由网易邮箱大师定制


On 05/13/2019 14:51，gtw<notifications@github.com> wrote：

我的测试用例很简单，里面只有两句话
import os
os.popen("adb devices")

**Comment by Macile** [comment]
![TIM图片20190513145414](https://user-images.githubusercontent.com/26572845/57601720-dbce1500-758f-11e9-8ccf-9caec6ed38fd.png)
这个是我的测试用例，但是依然是报这个错误
