### ISSUE TITLE
提示'Table' object has no attribute 'purge' 错误，是什么情况呢？

### ISSUE THREAD

**Issue by qugo9955** [pengchenglin/ATX-Test#5]
File "D:\Python36\lib\site-packages\tinydb\database.py", line 250, in __getattr__
    return getattr(self.table(self.default_table_name), name)
AttributeError: 'Table' object has no attribute 'purge'

**Comment by qugo9955** [comment]
能建一个交流群吗？遇到问题方便交流

**Comment by pengchenglin** [comment]
更新下tinydb的版本看看


| |
林鹏程
|
|
m170587788@163.com
|
签名由网易邮箱大师定制


在2020年09月2日 10:59，qugo9955<notifications@github.com> 写道：

File "D:\Python36\lib\site-packages\tinydb\database.py", line 250, in getattr
return getattr(self.table(self.default_table_name), name)
AttributeError: 'Table' object has no attribute 'purge'

**Comment by pengchenglin** [comment]
| |
林鹏程
|
|
m170587788@163.com
|
签名由网易邮箱大师定制


在2020年09月2日 11:00，qugo9955<notifications@github.com> 写道：

能建一个交流群吗？遇到问题方便交流

**Comment by qugo9955** [comment]
这个问题是由于我的  tinydb版本是4.0
4.0这个方法改为了truncate()。
解决方法：1、换方法名称；2、将tinydb版本降到4.0以下
